const SOCIAL_TYPE_VALUES = ['KAKAO', 'GOOGLE'] as const;
type SOCIAL_TYPE = typeof SOCIAL_TYPE_VALUES[number];

const CHALLENGE_CATEGORY_TYPE_VALUES = ['test1', 'test2', 'test3'] as const;
type CHALLENGE_CATEGORY_TYPE = typeof CHALLENGE_CATEGORY_TYPE_VALUES[number];

const CHALLENGE_FREQUENCY_TYPE_VALUES = ['1', '2', '3'] as const;
type CHALLENGE_FREQUENCY_TYPE = typeof CHALLENGE_FREQUENCY_TYPE_VALUES[number];

export {
  SOCIAL_TYPE_VALUES,
  SOCIAL_TYPE,
  CHALLENGE_CATEGORY_TYPE_VALUES,
  CHALLENGE_CATEGORY_TYPE,
  CHALLENGE_FREQUENCY_TYPE_VALUES,
  CHALLENGE_FREQUENCY_TYPE,
};
